# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lover_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='media',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.User'),
        ),
    ]
