# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20170610_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
