# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(default='story', max_length=40),
        ),
    ]
