# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_story_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='imgs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
