# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0009_myphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('modified_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MyPhoto',
        ),
        migrations.RemoveField(
            model_name='story',
            name='media',
        ),
        migrations.AlterModelTable(
            name='story',
            table=None,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='story',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Upload'),
        ),
    ]
