# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20170610_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='owner',
        ),
    ]
